# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.CharField(max_length=20)),
                ('datapesagem', models.DateField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=50)),
                ('datanasc', models.CharField(max_length=50)),
                ('altura', models.CharField(max_length=20)),
                ('peso_inicial', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=2)),
                ('datacadastro', models.DateField(max_length=50)),
                ('status', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='peso',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balanca.Pessoa'),
        ),
    ]
