# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='datanasc',
            field=models.DateField(max_length=50),
        ),
    ]
